name: Deploy git page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install python
        run: sudo apt install python3 python3-pip
      - name: Install deps
        run: pip3 install -r requirements.txt
      - name: Deploy
        run: mkdocs gh-deploy --remote-branch gh-pages --force
